### ISSUE TITLE
建议SwiftUI项目README里写好Getting Started，补上pod install部分

### ISSUE THREAD

**Issue by shuiRong** [ifanrx/hydrogen-demo#23]
我是新手，学了Swift后，就直接来学习SwiftUI写App了，因此不知道有的项目还得安装cocospod，检索了一番才知道。
所以为了方便后面的新手，建议补充好文档，或者把网上的[教程](https://www.jianshu.com/p/33217cfbe893)链接放上去。

**Comment by pqhifanr** [comment]
@shuiRong 感谢你的建议，我会尽快补充完善。有问题你可以先查看[知晓云iOS](https://doc.minapp.com/ios-sdk/)的文档，上面有比较详细的介绍。另外 [cocospod](https://cocoapods.org/) 是 iOS 第三方管理工具，通过这个工具可以方便快捷地集成第三方库。
