### ISSUE TITLE
bs-demo，地图黄页 app 总报错，找不到哪里有问题。

### ISSUE THREAD

**Issue by Chen-Hu** [ifanrx/hydrogen-demo#4]
VM2605:2 Failed to load image /pages/company/company : the server responded with a status of 404 (HTTP/1.1 404 Not Found) 
From server 127.0.0.1
![image](https://user-images.githubusercontent.com/6964498/31184043-e8992282-a95a-11e7-9f44-b7194e599571.png)
![image](https://user-images.githubusercontent.com/6964498/31184078-005c90fc-a95b-11e7-959d-c5b708950afb.png)

**Comment by TerenYeung** [comment]
出现这个问题的原因，可能是 image 的地址错误，你检查一下 image 标签的 src 属性值是否合法。

![error](http://upload-images.jianshu.io/upload_images/1993435-d24e57045ada12ea.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/600)

---

![success](http://upload-images.jianshu.io/upload_images/1993435-3f628a1deae8dae7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/600)
